- name: Install and start MySQL server
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt packages cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started