- name: установка dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: настройка dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: запуск dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

handlers:
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted