- name: Создание группы superusers
  hosts: localhost
  become: yes
  tasks:
    - name: Создание группы superusers
      group:
        name: superusers
        state: present

    - name: Добавление пользователей в группу superusers
      user:
        name: "{{ item }}"
        groups: superusers
      loop:
        - user2
        - user3

    - name: Настройка sudoers
      lineinfile:
        path: /etc/sudoers
        line: "%superusers ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'
      become: yes